name: test-release-action

description: sample workflow

inputs:
  node-version:
    description: Node.js version used for running tests etc
    required: false
    default: '14'
  github-token:
    description: PAT of a GitHub user which creates release PR
    required: true
  npm-token:
    description: PAT of an NPM user which publishes the package
    required: true
  run-tests:
    description: Whether to run tests prior to running release-please
    default: '1'
    required: false

outputs:
  release-created:
    description: If the release has been already created or it was just the release PR
    value: ${{ steps.release.outputs.release_created }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - run: npm test
      if: ${{ inputs.run-tests }}
      shell: bash
    - uses: codex-team/action-nodejs-package-info@v1
      id: package
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      with:
        token: ${{ inputs.github-token }}
        release-type: node
        package-name: ${{ steps.package.outputs.name }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
      if: ${{ steps.release.outputs.release_created }}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      if: ${{ steps.release.outputs.release_created }}
      shell: bash
